CREATE TABLE `llx2k_materiel` (
 `rowid` int(11) NOT NULL AUTO_INCREMENT,
 `fk_preinventaire` int(11) NOT NULL,
 `fk_type_materiel` int(10) NOT NULL,
 `precision_type` text DEFAULT NULL,
 `cote` int(11) NOT NULL,
 `fk_etat` int(11) NOT NULL,
 `fk_exploitabilite` int(11) NOT NULL,
 `fk_etat_etiquette` int(11) NOT NULL,
 `fk_marque` int(11) DEFAULT NULL,
 `modele` text DEFAULT NULL,
 `notes_supplementaires` mediumtext DEFAULT NULL,
 `fk_origine` int(11) DEFAULT NULL,
 `fk_entrepot` int(11) DEFAULT NULL,
 `fk_proprietaire` int(11) DEFAULT NULL,
 `date_ajout` timestamp NOT NULL DEFAULT current_timestamp(),
 `active` int(11) NOT NULL DEFAULT 1,
 `tms` timestamp NOT NULL DEFAULT current_timestamp(),
 `fk_user_author` int(11) NOT NULL,
 `fk_user_modif` int(11) DEFAULT NULL,
 `import_key` varchar(14) DEFAULT NULL,
 PRIMARY KEY (`rowid`),
 KEY `fk_type_materiel` (`fk_type_materiel`),
 KEY `fk_etat` (`fk_etat`),
 KEY `fk_etat_etiquette` (`fk_etat_etiquette`),
 KEY `fk_exploitabilite` (`fk_exploitabilite`),
 KEY `fk_entrepot` (`fk_entrepot`),
 KEY `fk_marque` (`fk_marque`),
 KEY `fk_origine` (`fk_origine`),
 KEY `fk_proprietaire` (`fk_proprietaire`),
 KEY `fk_preinventaire` (`fk_preinventaire`),
 CONSTRAINT `fk_entrepot` FOREIGN KEY (`fk_entrepot`) REFERENCES `llx2k_entrepot` (`rowid`) ON DELETE SET NULL,
 CONSTRAINT `fk_marque` FOREIGN KEY (`fk_marque`) REFERENCES `llx2k_c_marque` (`rowid`) ON DELETE SET NULL,
 CONSTRAINT `fk_origine` FOREIGN KEY (`fk_origine`) REFERENCES `llx2k_c_origine_materiel` (`rowid`) ON DELETE SET NULL,
 CONSTRAINT `fk_preinventaire` FOREIGN KEY (`fk_preinventaire`) REFERENCES `llx2k_preinventaire` (`rowid`) ON DELETE NO ACTION,
 CONSTRAINT `fk_proprietaire` FOREIGN KEY (`fk_proprietaire`) REFERENCES `llx2k_c_proprietaire` (`rowid`) ON DELETE SET NULL
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1