---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rovi9061/intranet.tousalamusique.com/custom
    - /bin cp * $DEPLOYPATH 
    # - /bin/cp -R adherents $DEPLOYPATH
    # - /bin/cp -R admin $DEPLOYPATH
    # - /bin/cp -R core $DEPLOYPATH
    # - /bin/cp -R default $DEPLOYPATH
    # - /bin/cp -R don $DEPLOYPATH
    # - /bin/cp -R donateur $DEPLOYPATH
    # - /bin/cp -R entretien $DEPLOYPATH
    # - /bin/cp -R exploitation $DEPLOYPATH
    # - /bin/cp -R kit $DEPLOYPATH
    # - /bin/cp -R management $DEPLOYPATH
    # - /bin/cp -R materiel $DEPLOYPATH
    # - /bin/cp -R md $DEPLOYPATH
    # - /bin/cp -R organisation $DEPLOYPATH
    # - /bin/cp -R phpdoc $DEPLOYPATH
    # - /bin/cp -R recherche $DEPLOYPATH
    # - /bin/cp -R recufiscal $DEPLOYPATH
    # - /bin/cp -R scolarite $DEPLOYPATH
    # - /bin/cp -R source $DEPLOYPATH
    # - /bin/cp -R test $DEPLOYPATH
    # - /bin/cp -R testdoccc $DEPLOYPATH
    # - /bin/cp -R viescolaire $DEPLOYPATH
    # - /bin/cp index.html $DEPLOYPATH
    # - /bin/cp main.inc.php $DEPLOYPATH
    # - /bin/cp proxy.md $DEPLOYPATH
    # - /bin/cp README.md $DEPLOYPATH