CREATE TABLE llx_c_type_classe(
	-- BEGIN MODULEBUILDER FIELDS
	rowid integer AUTO_INCREMENT PRIMARY KEY NOT NULL, 
	type varchar(255) NOT NULL, 
	active smallint NOT NULL

	-- END MODULEBUILDER FIELDS
) ENGINE=innodb;