CREATE TABLE llx_c_jour(
	-- BEGIN MODULEBUILDER FIELDS
	rowid integer AUTO_INCREMENT PRIMARY KEY NOT NULL, 
	jour varchar(255) NOT NULL, 
	active smallint NOT NULL

	-- END MODULEBUILDER FIELDS
) ENGINE=innodb;